name: Build and deploy package

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Build with dotnet
      run:  dotnet build ./ExtendedEnums/ExtendedEnums.sln --configuration Release

    - name: Test
      run: dotnet test ./ExtendedEnums/ExtendedEnums.Tests/

    - name: Create the Package
      run: dotnet pack ./ExtendedEnums/ExtendedEnums/ --configuration Release

    - name: Publish to Nuget
      run: dotnet nuget push "ExtendedEnums/ExtendedEnums/bin/Release/*.nupkg" -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json